name: CI

on:
  workflow_call:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release --no-restore

    - name: Publish
      if: github.ref == 'refs/heads/main'
      run: dotnet publish -c Release -p:PublishDir='${{ github.workspace }}/webapi'
 
    - name: Deploy webapp
      uses: azure/webapps-deploy@v2
      if: github.ref == 'refs/heads/main'
      with:
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{ github.workspace }}/webapi'